//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.16 at 03:10:43 PM ACST 
//


package domain.europe;


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponseResultDocIntStr_QNAME = new QName("", "str");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Response.Result }
     * 
     */
    public Response.Result createResponseResult() {
        return new Response.Result();
    }

    /**
     * Create an instance of {@link Response.Result.Doc }
     * 
     */
    public Response.Result.Doc createResponseResultDoc() {
        return new Response.Result.Doc();
    }

    /**
     * Create an instance of {@link Response.Lst }
     * 
     */
    public Response.Lst createResponseLst() {
        return new Response.Lst();
    }

    /**
     * Create an instance of {@link Response.Lst.Lst1 }
     * 
     */
    public Response.Lst.Lst1 createResponseLstLst1() {
        return new Response.Lst.Lst1();
    }

    /**
     * Create an instance of {@link Response.Result.Doc.Str }
     * 
     */
    public Response.Result.Doc.Str createResponseResultDocStr() {
        return new Response.Result.Doc.Str();
    }

    /**
     * Create an instance of {@link Response.Result.Doc.Date }
     * 
     */
    public Response.Result.Doc.Date createResponseResultDocDate() {
        return new Response.Result.Doc.Date();
    }

    /**
     * Create an instance of {@link Response.Result.Doc.Arr }
     * 
     */
    public Response.Result.Doc.Arr createResponseResultDocArr() {
        return new Response.Result.Doc.Arr();
    }

    /**
     * Create an instance of {@link Response.Result.Doc.Bool }
     * 
     */
    public Response.Result.Doc.Bool createResponseResultDocBool() {
        return new Response.Result.Doc.Bool();
    }

    /**
     * Create an instance of {@link Response.Result.Doc.Float }
     * 
     */
    public Response.Result.Doc.Float createResponseResultDocFloat() {
        return new Response.Result.Doc.Float();
    }

    /**
     * Create an instance of {@link Response.Result.Doc.Int }
     * 
     */
    public Response.Result.Doc.Int createResponseResultDocInt() {
        return new Response.Result.Doc.Int();
    }

    /**
     * Create an instance of {@link Response.Result.Doc.Long }
     * 
     */
    public Response.Result.Doc.Long createResponseResultDocLong() {
        return new Response.Result.Doc.Long();
    }

    /**
     * Create an instance of {@link Response.Lst.Int }
     * 
     */
    public Response.Lst.Int createResponseLstInt() {
        return new Response.Lst.Int();
    }

    /**
     * Create an instance of {@link Response.Lst.Lst1 .Str }
     * 
     */
    public Response.Lst.Lst1 .Str createResponseLstLst1Str() {
        return new Response.Lst.Lst1 .Str();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "str", scope = Response.Result.Doc.Int.class)
    public JAXBElement<String> createResponseResultDocIntStr(String value) {
        return new JAXBElement<String>(_ResponseResultDocIntStr_QNAME, String.class, Response.Result.Doc.Int.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "str", scope = Response.Result.Doc.Bool.class)
    public JAXBElement<String> createResponseResultDocBoolStr(String value) {
        return new JAXBElement<String>(_ResponseResultDocIntStr_QNAME, String.class, Response.Result.Doc.Bool.class, value);
    }

}
