spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nsprices_dev
    username: nsp_prod_user
    password: highway1
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: false